/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;

import demo.AmazonSearch;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // TestCases tests = new TestCases(); // Initialize your test class
        // tests.testCase01();
        // tests.endTest(); // End your test by clearning connections and closing browser

        // AmazonSearch amazon = new AmazonSearch();
        // amazon.testCase01();
        // amazon.endTest();

        // hyperlinksCount count = new hyperlinksCount();
        // count.testCase01();
        // count.endTest();

        // linkedInPost post=new linkedInPost();
        // post.testCase01();
        // post.endTest();

        // imageURLs bmsImage= new imageURLs();
        // bmsImage.testCase01();
        // bmsImage.endTest();

        NestedFrames frames = new NestedFrames();
        frames.testCase01();
        frames.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
